[package]
name = "video-frame-fuse"
version = "0.1.0"
authors = ["Colin Nolan <cn580@alumni.york.ac.uk>"]
edition = "2018"

[dependencies]
opencv = "0.46.3"
fuse = { git = "https://github.com/zargony/fuse-rs", rev="39fde4a5c47ce370d228ac190f950bd835db7f47" }
users = "0.11"
lazy_static = "1.4.0"
# For: collect_vec
#itertools = "0.10.0"
strum = "0.20"
strum_macros = "0.20"
cached = "0.22.0"
csv = "1.1.5"