[package]
name = "video-frame-fuse"
version = "0.1.0"
authors = ["Colin Nolan <cn580@alumni.york.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.46.3"
fuse = { git = "https://github.com/zargony/fuse-rs", rev="39fde4a5c47ce370d228ac190f950bd835db7f47" }
users = "0.11"
lazy_static = "1.4.0"
genawaiter = { version = "0.99.1", features = ["futures03", "proc_macro"] }
