FROM ubuntu:20.04 as builder

SHELL ["/bin/bash", "-c"]

# Note: not optimising layers in builder
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
        ca-certificates \
        curl
RUN curl -fsSL https://git.io/shellspec | sh -s -- --yes

