name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    pull_request:
      types:
        - opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Build
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          target: builder

      - name: Unit test
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          target: tester

      - name: Package
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          target: packager 
